[package]
name = "csrf"
version = "0.5.0"
edition = "2024"
authors = ["heartsucker <heartsucker@autistici.org>"]
description = "CSRF protection primitives"
homepage = "https://github.com/heartsucker/rust-csrf"
repository = "https://github.com/heartsucker/rust-csrf"
documentation = "https://docs.rs/csrf"
readme = "README.md"
license = "MIT"
keywords = ["csrf", "web", "security", "http"]
categories = ["web-programming", "authentication", "cryptography"]

[badges]
travis-ci = { repository = "heartsucker/rust-csrf", branch = "master" }
appveyor = { repository = "heartsucker/rust-csrf", branch = "master", service = "github" }

[features]
iron = ["typemap"]

[dependencies]
aead = "0.6.0-rc.10"
aes-gcm = "0.11.0-rc.3"
byteorder = "1"
chacha20poly1305 = "0.11.0-rc.3"
chrono = "0.4"
data-encoding = "2.10"
crypto-common = { version = "0.2.0", features = ["getrandom"] }
hmac = "0.13.0-rc.5"
sha2 = { version = "0.11.0-rc.5" }
thiserror = "2.0"
typemap = { version = "0.3", optional = true }
